# Generated by Django 3.2.23 on 2024-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
