# Generated by Django 3.2.23 on 2024-01-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20240131_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='joinable',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='public',
        ),
    ]
