# Generated by Django 3.2.23 on 2024-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20240131_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='joinable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
