# Generated by Django 3.2.23 on 2024-02-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20240201_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='joinable',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='public',
        ),
    ]
