# Generated by Django 3.2.23 on 2024-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20240201_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='joinable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
